env:
  EM_VERSION: 4.0.5
  EM_CACHE_FOLDER: "emsdk-cache"

on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup emscripten cache
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Build app
        run:
          make emscripten

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8ad41ca609d132c2543d121ea3a9bb8e
          projectName: 3to4pp
          directory: web
